import {useEffect,useMemo,useState} from "react";
import {motion,AnimatePresence} from "framer-motion";
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from "recharts";
import {LayoutDashboard,LineChart,BriefcaseBusiness,Star,ReceiptText,WalletCards,Bell,Settings,Search,Plus,X,Menu,TrendingUp,CircleDollarSign,CreditCard,Target,Trash2,Edit3,CheckCircle2,LogOut,Moon,ChevronRight,ArrowUpRight,ArrowDownRight} from "lucide-react";
import * as api from "./api";

type Stock={symbol:string;companyName:string;sector:string;currentPrice:number;previousPrice:number;marketCap:number;peRatio:number;high52:number;low52:number;currency?:string};
type MarketPoint={date:string;timestamp:number;price:number};
type PortfolioPoint={date:string;timestamp:number;value:number;invested:number;pnl:number};
type Tx={id:number;type:string;category:string;description:string;amount:number;date:string};
type Goal={id:number;name:string;targetAmount:number;currentAmount:number;targetDate:string};

const DEMO="tanay@finora.demo";
const seedStocks:Stock[]=[
 ["RELIANCE","Reliance Industries","Energy",1425.6,1392.1,19.3e12,24.8,1612,1150],
 ["TCS","Tata Consultancy Services","Technology",3421.2,3378.1,12.4e12,27.2,4592,3050],
 ["INFY","Infosys","Technology",1521.4,1554.7,6.32e12,24.1,1967,1350],
 ["HDFCBANK","HDFC Bank","Banking",1785.2,1762.3,13.6e12,20.4,1880,1363],
 ["TATAMOTORS","Tata Motors","Automobile",712.1,718.4,2.62e12,8.7,1179,608],
 ["ICICIBANK","ICICI Bank","Banking",1328.8,1312.5,9.35e12,18.9,1362,895],
 ["AAPL","Apple","Technology",182.42,176.8,28e12,29.3,237.49,164.08],
 ["NVDA","NVIDIA","Technology",184.72,179.25,45e12,52.1,195.95,75.61]
].map(x=>({symbol:x[0] as string,companyName:x[1] as string,sector:x[2] as string,currentPrice:x[3] as number,previousPrice:x[4] as number,marketCap:x[5] as number,peRatio:x[6] as number,high52:x[7] as number,low52:x[8] as number}));
const perf=[680000,701000,695000,735000,756000,782000,842650].map((v,i)=>({d:["Jun 1","Jun 6","Jun 11","Jun 16","Jun 21","Jun 26","Jun 30"][i],v}));
const money=(n:number)=>`₹${n.toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const stockMoney=(s:Stock)=>s.currency==="USD"?`$${s.currentPrice.toFixed(2)}`:money(s.currentPrice);
const pct=(a:number,b:number)=>((a-b)/b)*100;
const today=()=>new Date().toISOString().slice(0,10);
const displayDate=()=>new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());

const rangeCount=(range:string)=>({"1D":24,"1W":28,"1M":30,"6M":26,"1Y":52,"5Y":60} as Record<string,number>)[range]||30;
const stableSeed=(text:string)=>Array.from(text).reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),7);
const fallbackMarketHistory=(s:Stock,range:string):MarketPoint[]=>{
 const n=rangeCount(range), seed=stableSeed(s.symbol), end=s.currentPrice;
 const startFactor=0.88+((seed%17)/100);
 return Array.from({length:n},(_,i)=>{
   const t=n===1?1:i/(n-1);
   const wave=Math.sin((i+(seed%9))*0.55)*0.012+Math.cos((i+(seed%13))*0.21)*0.008;
   const price=end*(startFactor+(1-startFactor)*t+wave*(1-t*0.25));
   return {date:range==="1D"?`${String(Math.floor(i/4)+9).padStart(2,"0")}:${String((i%4)*15).padStart(2,"0")}`:`${range} · ${i+1}`,timestamp:i,price:Math.max(price,end*0.65)};
 });
};
const fallbackPortfolioHistory=(holdings:any[],stocks:Stock[],range:string,fx:number):PortfolioPoint[]=>{
 const n=rangeCount(range);
 const invested=holdings.reduce((sum,h)=>{const s=stocks.find(x=>x.symbol===h.symbol);return sum+h.qty*h.avg*(s?.currency==="USD"?fx:1)},0);
 const current=holdings.reduce((sum,h)=>{const s=stocks.find(x=>x.symbol===h.symbol);return sum+h.qty*(s?(s.currentPrice*(s.currency==="USD"?fx:1)):h.avg)},0);
 const seed=holdings.reduce((a,h)=>a+stableSeed(h.symbol),11);
 return Array.from({length:n},(_,i)=>{
   const t=n===1?1:i/(n-1);
   const trend=invested+(current-invested)*t;
   const movement=Math.sin((i+(seed%11))*0.42)*Math.max(invested*0.012,100)+Math.cos((i+3)*0.19)*Math.max(invested*0.006,50);
   const value=Math.max(0,trend+movement*(1-t*0.4));
   return {date:range==="1D"?`${String(Math.floor(i/4)+9).padStart(2,"0")}:${String((i%4)*15).padStart(2,"0")}`:`${range} · ${i+1}`,timestamp:i,value,invested,pnl:value-invested};
 });
};

function App(){
 const [auth,setAuth]=useState<"login"|"register">("login");
 const [logged,setLogged]=useState(false);
 const [page,setPage]=useState("Dashboard");
 const [mobile,setMobile]=useState(false);
 const [search,setSearch]=useState("");
 const [stocks,setStocks]=useState<Stock[]>(seedStocks);
 const [selected,setSelected]=useState<Stock|null>(null);
 const [invest,setInvest]=useState<Stock|null>(null);
 const [watch,setWatch]=useState<string[]>(["ICICIBANK","NVDA"]);
 const [holdings,setHoldings]=useState([{symbol:"RELIANCE",qty:12,avg:1320},{symbol:"TCS",qty:8,avg:3250},{symbol:"INFY",qty:15,avg:1555}]);
 const [txs,setTxs]=useState<Tx[]>([
  {id:1,type:"EXPENSE",category:"Food",description:"Dining & food",amount:820,date:today()},
  {id:2,type:"INCOME",category:"Salary",description:"Monthly income",amount:75000,date:today()},
  {id:3,type:"BUY",category:"Investment",description:"Reliance Industries",amount:15840,date:today()}
 ]);
 const [goals,setGoals]=useState<Goal[]>([
  {id:1,name:"Emergency fund",targetAmount:200000,currentAmount:85000,targetDate:"2027-03-31"},
  {id:2,name:"New laptop",targetAmount:120000,currentAmount:72000,targetDate:"2027-01-15"}
 ]);
 const [toast,setToast]=useState("");
 const [modal,setModal]=useState<"tx"|"income"|"goal"|"budget"|null>(null);
 const [editTx,setEditTx]=useState<Tx|null>(null);
 const [editGoal,setEditGoal]=useState<Goal|null>(null);
 const [portfolioRange,setPortfolioRange]=useState("1M");
 const [portfolioHistory,setPortfolioHistory]=useState<PortfolioPoint[]>([]);
 const [usdInr,setUsdInr]=useState(88);
 const [marketFilter,setMarketFilter]=useState("Trending");

 useEffect(()=>{
   if(!logged)return;
   const load=async()=>{
     try{
       const [live,port,fx,ph]=await Promise.all([api.getStocks(),api.getPortfolio(DEMO),api.getUsdInr().catch(()=>null),api.getPortfolioHistory(DEMO,portfolioRange)]);
       if(live?.length)setStocks(live);
       if(port?.length)setHoldings(port.map((h:any)=>({symbol:h.stock.symbol,qty:h.quantity,avg:h.averageBuyPrice})));
       if(fx?.usdInr)setUsdInr(fx.usdInr);
       if(ph?.points?.length)setPortfolioHistory(ph.points); else setPortfolioHistory(fallbackPortfolioHistory(holdings.length?holdings:[{symbol:"RELIANCE",qty:12,avg:1320},{symbol:"TCS",qty:8,avg:3250},{symbol:"INFY",qty:15,avg:1555}], live?.length?live:seedStocks, usdInr, portfolioRange));
     }catch{}
   };
   load();
   const timer=setInterval(async()=>{
     try{
       const live=await api.getStocks();
       if(live?.length)setStocks(live);
       const ph=await api.getPortfolioHistory(DEMO,portfolioRange);
       if(ph?.points?.length)setPortfolioHistory(ph.points); else setPortfolioHistory(fallbackPortfolioHistory(holdings,stocks,portfolioRange,usdInr));
     }catch{}
   },60000);
   return()=>clearInterval(timer);
 },[logged,portfolioRange]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)}},[toast]);

 if(!logged) return <Auth mode={auth} setMode={setAuth} onLogin={()=>setLogged(true)}/>;

 const filtered=stocks.filter(s=>(s.companyName+" "+s.symbol+" "+s.sector).toLowerCase().includes(search.toLowerCase()));
 const fxValue=(s:Stock)=>s.currency==="USD"?s.currentPrice*usdInr:s.currentPrice;
 const portfolioValue=holdings.reduce((sum,h)=>{const s=stocks.find(x=>x.symbol===h.symbol);return sum+(s?fxValue(s)*h.qty:0)},0);
 const investedValue=holdings.reduce((sum,h)=>sum+h.qty*h.avg*(stocks.find(x=>x.symbol===h.symbol)?.currency==="USD"?usdInr:1),0);
 const totalReturn=portfolioValue-investedValue;
 const todayPnl=holdings.reduce((sum,h)=>{const s=stocks.find(x=>x.symbol===h.symbol);return sum+(s?(fxValue(s)-((s.currency==="USD"?usdInr:1)*s.previousPrice))*h.qty:0)},0);
 const income=txs.filter(x=>x.type==="INCOME").reduce((a,x)=>a+x.amount,0);
 const expense=txs.filter(x=>x.type==="EXPENSE").reduce((a,x)=>a+x.amount,0);
 const investedSpending=txs.filter(x=>x.type==="BUY").reduce((a,x)=>a+x.amount,0);
 const cashAvailable=52400+income-expense-investedSpending;

 const nav=(p:string)=>{setPage(p);setSelected(null);setMobile(false)};
 const toggleWatch=(symbol:string)=>setWatch(w=>w.includes(symbol)?w.filter(x=>x!==symbol):[...w,symbol]);

 const buy=async(amount:number)=>{
   if(!invest||amount<=0){setToast("Enter a valid amount");return}
   const q=amount/invest.currentPrice;
   setHoldings(h=>{const old=h.find(x=>x.symbol===invest.symbol);if(!old)return[...h,{symbol:invest.symbol,qty:q,avg:invest.currentPrice}];return h.map(x=>x.symbol===old.symbol?{...x,qty:x.qty+q,avg:(x.qty*x.avg+amount)/(x.qty+q)}:x)});
   setTxs(t=>[{id:Date.now(),type:"BUY",category:"Investment",description:invest.companyName,amount,date:today()},...t]);
   try{await api.invest(DEMO,invest.symbol,amount)}catch{}
   setInvest(null);
   try{
     const ph=await api.getPortfolioHistory(DEMO,portfolioRange);
     if(ph?.points)setPortfolioHistory(ph.points);
     const live=await api.getStocks();
     if(live?.length)setStocks(live);
   }catch{}
   setToast(`Investment of ${money(amount)} added to ${invest.symbol}`);
 };

 const addTx=(t:Omit<Tx,"id">)=>{setTxs(x=>[{...t,id:Date.now()},...x]);setModal(null);setToast("Transaction added");};
 const updateTx=(t:Tx)=>{setTxs(x=>x.map(a=>a.id===t.id?t:a));setEditTx(null);setToast("Transaction updated");};
 const removeTx=(id:number)=>{setTxs(x=>x.filter(t=>t.id!==id));setToast("Transaction deleted");};
 const addGoal=(g:Omit<Goal,"id">)=>{setGoals(x=>[...x,{...g,id:Date.now()}]);setModal(null);setToast("Goal created");};
 const updateGoal=(g:Goal)=>{setGoals(x=>x.map(a=>a.id===g.id?g:a));setEditGoal(null);setToast("Goal updated");};
 const removeGoal=(id:number)=>{setGoals(x=>x.filter(g=>g.id!==id));setToast("Goal deleted");};

 return <div className="min-h-screen bg-[#080b12] text-slate-100">
  <AnimatePresence>{toast&&<motion.div initial={{y:-20,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-20,opacity:0}} className="fixed right-5 top-5 z-[80] flex items-center gap-3 rounded-2xl border border-emerald-400/20 bg-[#101722] px-5 py-4 shadow-2xl"><CheckCircle2 className="text-emerald-400" size={19}/>{toast}</motion.div>}</AnimatePresence>
  <aside className={`fixed z-50 h-screen w-64 border-r border-white/5 bg-[#0b0f17] p-5 transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}>
   <div className="flex items-center justify-between px-2 py-3"><button onClick={()=>nav("Dashboard")} className="text-2xl font-extrabold">fin<span className="gradient-text">ora</span></button><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div>
   <div className="mt-8 space-y-1">{[["Dashboard",LayoutDashboard],["Markets",LineChart],["Portfolio",BriefcaseBusiness],["Watchlist",Star],["Transactions",ReceiptText],["Budgets",WalletCards],["Finance",CreditCard]].map(([n,I]:any)=><button key={n} onClick={()=>nav(n)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${page===n?"bg-indigo-500/15 text-indigo-300":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><I size={18}/>{n}</button>)}</div>
   <div className="my-7 border-t border-white/5"/>
   {[["Notifications",Bell],["Settings",Settings]].map(([n,I]:any)=><button key={n} onClick={()=>nav(n)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${page===n?"bg-indigo-500/15 text-indigo-300":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><I size={18}/>{n}</button>)}
   <button onClick={()=>{setLogged(false);setPage("Dashboard")}} className="absolute bottom-5 left-5 right-5 flex items-center gap-3 rounded-xl border border-white/5 p-3 text-left hover:bg-white/5"><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-blue-400 to-violet-500 font-bold">T</div><div className="flex-1"><b className="text-sm">Tanay</b><div className="text-xs text-slate-500">Sign out</div></div><LogOut size={16}/></button>
  </aside>
  <div className="lg:pl-64">
   <header className="sticky top-0 z-30 border-b border-white/5 bg-[#080b12]/85 px-5 py-4 backdrop-blur-xl lg:px-8">
    <div className="flex items-center gap-4"><button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="relative max-w-xl flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);if(e.target.value)nav("Markets")}} placeholder="Search stocks, companies or symbols..." className="w-full rounded-2xl border border-white/5 bg-[#111722] py-3 pl-11 pr-4 text-sm outline-none focus:border-indigo-400/40"/>{search&&<div className="absolute top-14 left-0 right-0 z-40 overflow-hidden rounded-2xl border border-white/10 bg-[#101722] shadow-2xl">{filtered.slice(0,6).map(s=><button className="flex w-full items-center justify-between p-4 text-left hover:bg-white/5" key={s.symbol} onClick={()=>{setSelected(s);setSearch("")}}><span><b>{s.companyName}</b><small className="muted block">{s.symbol} · {s.sector}</small></span><span className={pct(s.currentPrice,s.previousPrice)>=0?"green":"red"}>{pct(s.currentPrice,s.previousPrice).toFixed(2)}%</span></button>)}</div>}</div><button onClick={()=>nav("Notifications")} className="grid h-11 w-11 place-items-center rounded-xl border border-white/5 bg-[#111722] text-slate-400 hover:text-white"><Bell size={18}/></button><button onClick={()=>nav("Settings")} className="hidden h-11 w-11 place-items-center rounded-xl border border-white/5 bg-[#111722] text-slate-400 hover:text-white sm:grid"><Settings size={18}/></button></div>
   </header>
   <main className="mx-auto max-w-[1500px] p-5 lg:p-8">
    {selected?<Company s={selected} watch={watch} toggle={()=>toggleWatch(selected.symbol)} onBack={()=>setSelected(null)} onInvest={()=>setInvest(selected)}/>:<>
     {page==="Dashboard"&&<Dashboard total={portfolioValue} invested={investedValue} todayPnl={todayPnl} cash={cashAvailable} fx={usdInr} history={portfolioHistory} range={portfolioRange} setRange={setPortfolioRange} holdings={holdings} stocks={stocks} select={setSelected} nav={nav}/>}
     {page==="Markets"&&<Markets stocks={filtered} select={setSelected} watch={watch} toggle={toggleWatch} invest={setInvest} filter={marketFilter} setFilter={setMarketFilter}/>}
     {page==="Portfolio"&&<Portfolio holdings={holdings} stocks={stocks} total={portfolioValue} invested={investedValue} returns={totalReturn} history={portfolioHistory} range={portfolioRange} setRange={setPortfolioRange} select={setSelected} fx={usdInr}/>}
     {page==="Watchlist"&&<Watch stocks={stocks.filter(s=>watch.includes(s.symbol))} select={setSelected} remove={toggleWatch}/>}
     {page==="Transactions"&&<TransactionPage txs={txs} openAdd={()=>{setEditTx(null);setModal("tx")}} edit={setEditTx} remove={removeTx}/>}
     {page==="Budgets"&&<Budgets open={()=>setModal("budget")}/>}
     {page==="Finance"&&<Finance income={income} expense={expense} txs={txs} goals={goals} addTx={()=>{setEditTx(null);setModal("tx")}} addIncome={()=>setModal("income")} addGoal={()=>{setEditGoal(null);setModal("goal")}} editTx={setEditTx} removeTx={removeTx} editGoal={setEditGoal} removeGoal={removeGoal}/>}
     {page==="Notifications"&&<Notifications toast={setToast}/>}
     {page==="Settings"&&<SettingsPage toast={setToast}/>}
    </>}
   </main>
  </div>
  <AnimatePresence>{invest&&<InvestModal s={invest} close={()=>setInvest(null)} buy={buy}/>}</AnimatePresence>
  <AnimatePresence>{modal==="tx"&&<TxModal initial={editTx} close={()=>setModal(null)} save={editTx?updateTx:addTx}/>}</AnimatePresence>
  <AnimatePresence>{modal==="income"&&<IncomeModal close={()=>setModal(null)} save={addTx}/>}</AnimatePresence>
  <AnimatePresence>{modal==="goal"&&<GoalModal initial={editGoal} close={()=>setModal(null)} save={editGoal?updateGoal:addGoal}/>}</AnimatePresence>
  <AnimatePresence>{modal==="budget"&&<BudgetModal close={()=>setModal(null)} toast={setToast}/>}</AnimatePresence>
 </div>
}

function Auth({mode,setMode,onLogin}:{mode:"login"|"register";setMode:any;onLogin:()=>void}){
 const [email,setEmail]=useState(DEMO),[pass,setPass]=useState("demo123"),[name,setName]=useState(""),[err,setErr]=useState("");
 const submit=(e:any)=>{e.preventDefault();if(!email||!pass||(mode==="register"&&!name)){setErr("Please complete all fields.");return}if(mode==="login"&&(email!==DEMO||pass!=="demo123")){setErr("For the demo, use tanay@finora.demo / demo123");return}onLogin()};
 return <div className="min-h-screen grid lg:grid-cols-2 bg-[#080b12]"><div className="hidden lg:flex relative overflow-hidden p-14"><div className="absolute -left-32 -top-32 h-96 w-96 rounded-full bg-indigo-500/15 blur-3xl"/><div className="absolute bottom-0 right-0 h-96 w-96 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative flex max-w-xl flex-col justify-between"><button className="text-3xl font-extrabold">fin<span className="gradient-text">ora</span></button><div><div className="text-sm text-indigo-300">PREMIUM FINANCE OS</div><h1 className="mt-4 text-6xl font-extrabold leading-[1.05]">Build wealth<br/><span className="gradient-text">with clarity.</span></h1><p className="muted mt-6 max-w-md text-lg leading-8">Track your money, discover investments and turn financial goals into a plan you can actually see.</p></div><div className="grid grid-cols-3 gap-3"><Mini label="Portfolio" value="₹8.42L"/><Mini label="Return" value="+12.48%"/><Mini label="Goals" value="02 active"/></div></div></div><div className="flex items-center justify-center p-6 lg:p-14"><div className="w-full max-w-md"><div className="mb-10 lg:hidden text-3xl font-extrabold">fin<span className="gradient-text">ora</span></div><div className="card p-8 lg:p-10"><div className="muted text-sm">{mode==="login"?"WELCOME BACK":"GET STARTED"}</div><h2 className="mt-2 text-3xl font-bold">{mode==="login"?"Sign in to Finora":"Create your Finora account"}</h2><p className="muted mt-2 text-sm">{mode==="login"?"Your financial command center is waiting.":"Set up your personal finance workspace."}</p><form onSubmit={submit} className="mt-8 space-y-4">{mode==="register"&&<Field label="Full name" value={name} set={setName} placeholder="Your name"/>}<Field label="Email" value={email} set={setEmail} placeholder="you@example.com"/><Field label="Password" type="password" value={pass} set={setPass} placeholder="••••••••"/>{err&&<div className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-300">{err}</div>}<button className="w-full rounded-xl bg-indigo-500 py-3.5 font-semibold hover:bg-indigo-400">{mode==="login"?"Sign in":"Create account"}</button></form><button onClick={()=>{setMode(mode==="login"?"register":"login");setErr("")}} className="mt-5 w-full text-sm text-slate-400 hover:text-white">{mode==="login"?"New to Finora? Create an account":"Already have an account? Sign in"}</button><div className="mt-6 rounded-xl bg-white/[.025] p-3 text-center text-xs text-slate-500">Demo: tanay@finora.demo · demo123</div></div></div></div></div>
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="text-xs text-slate-500">{label}</div><b className="mt-1 block">{value}</b></div>}
function Field({label,value,set,placeholder,type="text"}:{label:string;value:string;set:any;placeholder:string;type?:string}){return <label className="block text-sm"><span className="mb-2 block text-slate-300">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-white/10 bg-[#0b0f17] px-4 py-3 outline-none focus:border-indigo-400/50"/></label>}
function Stat({title,value,change,icon:I}:any){return <div className="card p-5"><div className="flex justify-between"><span className="muted text-sm">{title}</span><I size={18} className="text-indigo-300"/></div><b className="mt-4 block text-2xl">{value}</b>{change&&<span className={change.startsWith("-")?"red":"green"}>{change}</span>}</div>}
function Dashboard({total,invested,todayPnl,cash,fx,history,range,setRange,holdings,stocks,select,nav}:any){
 const chartHistory=history&&history.length?history:fallbackPortfolioHistory(holdings,stocks,range,fx);
 const last=chartHistory[chartHistory.length-1]?.value ?? total;
 const pnl=chartHistory[chartHistory.length-1]?.pnl ?? (total-invested);
 return <div className="space-y-7"><div><div className="muted text-sm">{displayDate()}</div><h1 className="mt-1 text-3xl font-bold">Good morning, Tanay 👋</h1><p className="muted mt-2">Your money, investments and goals — all in one clear view.</p></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Stat title="Total portfolio" value={money(last)} change={`${pnl>=0?"+":""}${money(pnl)}`} icon={BriefcaseBusiness}/><Stat title="Today's P&L" value={`${todayPnl>=0?"+":""}${money(todayPnl)}`} change={`${todayPnl>=0?"+":""}${total?((todayPnl/Math.max(invested,1))*100).toFixed(2):"0.00"}%`} icon={TrendingUp}/><Stat title="Cash available" value={money(cash)} icon={CircleDollarSign}/><Stat title="Monthly savings" value={money(Math.max(0,cash))} icon={Target}/></div>
 <div className="grid gap-5 xl:grid-cols-[1.6fr_.7fr]"><div className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="muted text-sm">Portfolio performance</span><b className="mt-1 block text-2xl">{money(last)}</b><small className={pnl>=0?"green":"red"}>{pnl>=0?"+":""}{money(pnl)} total P&L</small></div><div className="flex gap-1">{["1D","1W","1M","6M","1Y","5Y"].map(x=><button key={x} onClick={()=>setRange(x)} className={`rounded-lg px-3 py-1.5 text-xs ${range===x?"bg-white/10 text-white":"text-slate-500 hover:text-white"}`}>{x}</button>)}</div></div><div className="mt-6 h-[310px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartHistory}><XAxis dataKey="date" stroke="#475569" tickLine={false} axisLine={false}/><YAxis hide/><Tooltip contentStyle={{background:"#111722",border:"1px solid #263044",borderRadius:12}} formatter={(v:any)=>money(Number(v))}/><Area dataKey="value" stroke={pnl>=0?"#22c55e":"#ef4444"} fill="none" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="mt-3 text-xs text-slate-500">Market-linked portfolio value • updates automatically while the market data provider is available.</div></div>
 <div className="card p-6"><span className="muted text-sm">Quick actions</span><div className="mt-5 space-y-2">{[["Invest in a stock","Markets",LineChart],["View portfolio","Portfolio",BriefcaseBusiness],["Add transaction","Transactions",Plus],["Set a goal","Finance",Target]].map(([a,b,I]:any)=><button key={a} onClick={()=>nav(b)} className="flex w-full items-center gap-3 rounded-xl bg-white/[.025] p-4 text-left hover:bg-white/5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-500/10 text-indigo-300"><I size={17}/></span><span className="flex-1 text-sm font-medium">{a}</span><ChevronRight size={16} className="text-slate-600"/></button>)}</div></div></div>
 <div className="card overflow-hidden"><div className="flex justify-between border-b border-white/5 p-5"><b>Your holdings</b><button onClick={()=>nav("Portfolio")} className="text-sm text-indigo-300">View all →</button></div>{holdings.map((h:any)=>{const s=stocks.find((x:Stock)=>x.symbol===h.symbol);const r=s?pct(s.currentPrice,h.avg):0;return <button key={h.symbol} onClick={()=>s&&select(s)} className="flex w-full justify-between border-b border-white/5 p-5 text-left last:border-0 hover:bg-white/[.025]"><span><b>{h.symbol}</b><small className="muted block">{s?.companyName} · {h.qty.toFixed(2)} shares</small></span><span className="text-right"><b>{s?money((s.currency==="USD"?s.currentPrice*fx:s.currentPrice)*h.qty):money(0)}</b><small className={`block ${r>=0?"green":"red"}`}>{r.toFixed(2)}%</small></span></button>})}</div></div>}
function Markets({stocks,select,watch,toggle,invest,filter,setFilter}:any){
 const visible=stocks.filter((s:Stock)=>{
   if(filter==="Technology")return s.sector==="Technology";
   if(filter==="Banking")return s.sector==="Banking";
   if(filter==="Automobile")return s.sector==="Automobile";
   if(filter==="Energy")return s.sector==="Energy";
   if(filter==="Top Gainers")return pct(s.currentPrice,s.previousPrice)>0;
   if(filter==="Top Losers")return pct(s.currentPrice,s.previousPrice)<0;
   return true;
 });
 return <div className="space-y-7"><div><div className="muted text-sm">Markets</div><h1 className="mt-1 text-3xl font-bold">Discover investments</h1><p className="muted mt-2">Live market-linked prices and individual company performance.</p></div><div className="flex flex-wrap gap-2">{["Trending","Top Gainers","Top Losers","Technology","Banking","Automobile","Energy"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-xl border px-4 py-2 text-sm ${filter===x?"border-indigo-400/20 bg-indigo-500/10 text-indigo-300":"border-white/5 bg-white/[.02] text-slate-400 hover:text-white"}`}>{x}</button>)}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((s:Stock)=><StockCard key={s.symbol} s={s} select={select} watching={watch.includes(s.symbol)} toggle={()=>toggle(s.symbol)} invest={()=>invest(s)}/>)}</div></div>}
function StockCard({s,select,watching,toggle,invest}:any){const p=pct(s.currentPrice,s.previousPrice);return <motion.div whileHover={{y:-3}} className="card p-5"><div className="flex justify-between"><button onClick={()=>select(s)} className="flex items-center gap-3 text-left"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/5 font-bold">{s.symbol.slice(0,2)}</div><span><b>{s.companyName}</b><small className="muted block">{s.symbol} · {s.sector}</small></span></button><button onClick={toggle} className={watching?"text-amber-300":"text-slate-600 hover:text-white"}><Star size={19} fill={watching?"currentColor":"none"}/></button></div><div className="mt-6 flex justify-between"><div><b className="text-2xl">{stockMoney(s)}</b><div className={p>=0?"green":"red"}>{p>=0?"+":""}{p.toFixed(2)}%</div></div><div className="text-right text-xs text-slate-500">P/E<br/><b className="text-slate-200">{s.peRatio}</b></div></div><div className="mt-5 flex gap-2"><button onClick={()=>select(s)} className="flex-1 rounded-xl border border-white/10 py-2.5 text-sm hover:bg-white/5">View</button><button onClick={invest} className="flex-1 rounded-xl bg-indigo-500 py-2.5 text-sm font-semibold hover:bg-indigo-400">Invest</button></div></motion.div>}
function Company({s,watch,toggle,onBack,onInvest}:any){
 const [range,setRange]=useState("1M"); const [history,setHistory]=useState<MarketPoint[]>([]);
 const [loading,setLoading]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);api.getStockHistory(s.symbol,range).then((r:any)=>{if(active)setHistory(r?.points?.length?r.points:fallbackMarketHistory(s,range))}).catch(()=>active&&setHistory(fallbackMarketHistory(s,range))).finally(()=>active&&setLoading(false));return()=>{active=false}},[s.symbol,range]);
 const p=pct(s.currentPrice,s.previousPrice); const positive=p>=0;
 return <div className="space-y-6"><button onClick={onBack} className="muted text-sm hover:text-white">← Back to markets</button><div className="grid gap-5 xl:grid-cols-[1.6fr_.7fr]"><div className="card p-6"><div className="flex justify-between gap-4"><div><h1 className="text-2xl font-bold">{s.companyName}</h1><div className="muted">{s.symbol} · {s.sector}</div><b className="mt-6 block text-4xl">{stockMoney(s)}</b><div className={positive?"green":"red"}>{p>=0?"+":""}{p.toFixed(2)}% today</div></div><div className="flex gap-2"><button onClick={toggle} className="rounded-xl border border-white/10 px-4 py-2">{watch?"★ Watching":"☆ Watchlist"}</button><button onClick={onInvest} className="rounded-xl bg-indigo-500 px-5 py-2 font-semibold">Invest</button></div></div><div className="mt-8 flex flex-wrap gap-2">{["1D","1W","1M","6M","1Y","5Y"].map(x=><button key={x} onClick={()=>setRange(x)} className={`rounded-lg px-3 py-2 text-xs ${range===x?"bg-white/10 text-white":"text-slate-500 hover:text-white"}`}>{x}</button>)}</div><div className="mt-4 h-[330px]">{loading?<div className="grid h-full place-items-center muted">Loading market history…</div>:<ResponsiveContainer width="100%" height="100%"><AreaChart data={history.length?history:fallbackMarketHistory(s,range)}><XAxis dataKey="date" hide/><YAxis hide domain={["auto","auto"]}/><Tooltip contentStyle={{background:"#111722",border:"1px solid #263044",borderRadius:12}} formatter={(v:any)=>s.currency==="USD"?`$${Number(v).toFixed(2)}`:money(Number(v))}/><Area dataKey="price" stroke={positive?"#22c55e":"#ef4444"} fill="none" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>{range} market history</span><span>{s.currency==="USD"?"USD":"INR"} • simulated investing only</span></div></div><div className="card p-6"><b>Market snapshot</b><div className="mt-6 space-y-5">{[["Market cap",`₹${(s.marketCap/1e12).toFixed(1)}T`],["P/E",s.peRatio],["52W high",money(s.high52)],["52W low",money(s.low52)],["Sector",s.sector],["Currency",s.currency||"INR"]].map(x=><div className="flex justify-between border-b border-white/5 pb-4" key={x[0]}><span className="muted text-sm">{x[0]}</span><b>{x[1]}</b></div>)}</div></div></div><div className="card p-6"><b>About {s.companyName}</b><p className="muted mt-3 text-sm leading-7">Market prices and history are requested from a public market-data provider through the Finora backend. Investment actions remain simulated and do not place real trades.</p></div></div>}
function Portfolio({holdings,stocks,total,invested,returns,history,range,setRange,select,fx}:any){
 const chartHistory=(history&&history.length?history:fallbackPortfolioHistory(holdings,stocks,range,fx)); const latest=chartHistory[chartHistory.length-1]?.value??total; const pnl=chartHistory[chartHistory.length-1]?.pnl??returns;
 return <div className="space-y-7"><div><div className="muted text-sm">Portfolio</div><h1 className="mt-1 text-3xl font-bold">Your investments</h1><p className="muted mt-2">Value and P&L are calculated from your holdings and current market prices.</p></div><div className="grid gap-4 md:grid-cols-3"><Stat title="Portfolio value" value={money(latest)} change={`${pnl>=0?"+":""}${money(pnl)}`} icon={BriefcaseBusiness}/><Stat title="Invested" value={money(invested)} icon={WalletCards}/><Stat title="Total returns" value={`${pnl>=0?"+":""}${money(pnl)}`} change={`${invested?((pnl/invested)*100).toFixed(2):"0.00"}%`} icon={TrendingUp}/></div><div className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>Portfolio value</b><small className="muted ml-2">based on current holdings</small></div><div className="flex gap-1">{["1D","1W","1M","6M","1Y","5Y"].map(x=><button key={x} onClick={()=>setRange(x)} className={`rounded-lg px-3 py-1.5 text-xs ${range===x?"bg-white/10 text-white":"text-slate-500 hover:text-white"}`}>{x}</button>)}</div></div><div className="mt-5 h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartHistory}><XAxis dataKey="date" hide/><YAxis hide/><Tooltip contentStyle={{background:"#111722",border:"1px solid #263044",borderRadius:12}} formatter={(v:any)=>money(Number(v))}/><Area dataKey="value" stroke={pnl>=0?"#22c55e":"#ef4444"} fill="none" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="mt-3 text-xs text-slate-500">Invested: {money(invested)} • P&L: <span className={pnl>=0?"green":"red"}>{pnl>=0?"+":""}{money(pnl)}</span></div></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="muted bg-white/[.02] text-xs uppercase"><tr>{["Company","Qty","Avg","Current","Value","P&L"].map(x=><th className="p-5" key={x}>{x}</th>)}</tr></thead><tbody>{holdings.map((h:any)=>{const s=stocks.find((x:Stock)=>x.symbol===h.symbol);const multiplier=s?.currency==="USD"?fx:1;const current=(s?.currentPrice||0)*multiplier;const cost=h.avg*multiplier;const r=current-cost;return <tr className="cursor-pointer border-t border-white/5 hover:bg-white/[.025]" onClick={()=>s&&select(s)} key={h.symbol}><td className="p-5"><b>{h.symbol}</b><small className="muted block">{s?.companyName}</small></td><td className="p-5">{h.qty.toFixed(2)}</td><td className="p-5">{money(cost)}</td><td className="p-5">{money(current)}</td><td className="p-5">{money(current*h.qty)}</td><td className={`p-5 font-semibold ${r>=0?"green":"red"}`}>{r>=0?"+":""}{money(r*h.qty)} · {((r/Math.max(cost,1))*100).toFixed(2)}%</td></tr>})}</tbody></table></div></div></div>}
function Watch({stocks,select,remove}:any){return <div className="space-y-7"><h1 className="text-3xl font-bold">Watchlist</h1><div className="grid gap-4 md:grid-cols-2">{stocks.length?stocks.map((s:Stock)=><div className="card flex items-center justify-between p-5" key={s.symbol}><button onClick={()=>select(s)} className="text-left"><b>{s.companyName}</b><small className="muted block">{s.symbol}</small></button><div className="text-right"><b>{money(s.currentPrice)}</b><div className={pct(s.currentPrice,s.previousPrice)>=0?"green":"red"}>{pct(s.currentPrice,s.previousPrice).toFixed(2)}%</div></div><button onClick={()=>remove(s.symbol)} className="text-slate-500 hover:text-red-400"><X/></button></div>):<Empty title="Watchlist is empty" text="Star a stock in Markets to add it."/>}</div></div>}
function TransactionPage({txs,openAdd,edit,remove}:any){return <div className="space-y-7"><div className="flex items-end justify-between"><div><div className="muted text-sm">Money activity</div><h1 className="mt-1 text-3xl font-bold">Transactions</h1></div><button onClick={openAdd} className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-3 text-sm font-semibold"><Plus size={17}/> Add transaction</button></div><div className="card overflow-hidden">{txs.map((t:Tx)=><div className="flex items-center gap-4 border-b border-white/5 p-5 last:border-0"><div className={`grid h-10 w-10 place-items-center rounded-xl ${t.type==="EXPENSE"?"bg-red-500/10 text-red-300":"bg-emerald-500/10 text-emerald-300"}`}>{t.type==="EXPENSE"?<ArrowDownRight size={18}/>:<ArrowUpRight size={18}/>}</div><div className="flex-1"><b>{t.description}</b><small className="muted block">{t.category} · {t.date}</small></div><b className={t.type==="EXPENSE"?"red":"green"}>{t.type==="EXPENSE"?"-":"+"}{money(t.amount)}</b><button onClick={()=>edit(t)} className="text-slate-500 hover:text-white"><Edit3 size={16}/></button><button onClick={()=>remove(t.id)} className="text-slate-500 hover:text-red-400"><Trash2 size={16}/></button></div>)}</div></div>}
function Finance({income,expense,txs,goals,addTx,addIncome,addGoal,editTx,removeTx,editGoal,removeGoal}:any){const [tab,setTab]=useState("Overview");return <div className="space-y-7"><div><div className="muted text-sm">Personal finance</div><h1 className="mt-1 text-3xl font-bold">Your financial life, in one place.</h1><p className="muted mt-2">{displayDate()}</p></div><div className="flex gap-2 overflow-x-auto">{["Overview","Transactions","Income","Goals"].map(x=><button onClick={()=>setTab(x)} key={x} className={`rounded-xl px-4 py-2.5 text-sm ${tab===x?"bg-indigo-500 text-white":"bg-white/[.03] text-slate-400 hover:text-white"}`}>{x}</button>)}</div>{tab==="Overview"&&<><div className="grid gap-4 md:grid-cols-3"><Stat title="Monthly income" value={money(income)} icon={CircleDollarSign}/><Stat title="Monthly expenses" value={money(expense)} change="-8.2%" icon={CreditCard}/><Stat title="Monthly savings" value={money(income-expense)} change="+14.2%" icon={Target}/></div><div className="grid gap-5 lg:grid-cols-2"><div className="card p-6"><b>Money snapshot</b><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={[{x:"Week 1",i:18000,e:6200},{x:"Week 2",i:18000,e:8100},{x:"Week 3",i:19000,e:4900},{x:"Week 4",i:20000,e:6200}]}><XAxis dataKey="x" stroke="#475569"/><YAxis hide/><Tooltip contentStyle={{background:"#111722",border:"1px solid #263044",borderRadius:12}}/><Area dataKey="i" stroke="#22c55e" fill="none"/><Area dataKey="e" stroke="#ef4444" fill="none"/></AreaChart></ResponsiveContainer></div></div><div className="card p-6"><b>Quick finance actions</b><div className="mt-5 space-y-2"><button onClick={addIncome} className="w-full rounded-xl bg-emerald-500/10 p-4 text-left text-emerald-300 hover:bg-emerald-500/15">+ Add monthly income</button><button onClick={addTx} className="w-full rounded-xl bg-indigo-500/10 p-4 text-left text-indigo-300 hover:bg-indigo-500/15">+ Add transaction</button><button onClick={addGoal} className="w-full rounded-xl bg-violet-500/10 p-4 text-left text-violet-300 hover:bg-violet-500/15">+ Create financial goal</button></div></div></div></>}{tab==="Transactions"&&<TransactionPage txs={txs} openAdd={addTx} edit={editTx} remove={removeTx}/>} {tab==="Income"&&<IncomeSection income={income} add={addIncome}/>} {tab==="Goals"&&<Goals goals={goals} add={addGoal} edit={editGoal} remove={removeGoal}/>}</div>}
function IncomeSection({income,add}:any){return <div className="card p-7"><div className="flex items-center justify-between"><div><div className="muted text-sm">Current month</div><h2 className="mt-1 text-3xl font-bold">{money(income)}</h2><p className="muted mt-2">Create your monthly income and keep it in your transaction history.</p></div><button onClick={add} className="rounded-xl bg-indigo-500 px-4 py-3 text-sm font-semibold">+ Add income</button></div></div>}
function Goals({goals,add,edit,remove}:any){return <div className="space-y-4"><div className="flex justify-end"><button onClick={add} className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-3 text-sm font-semibold"><Plus size={17}/> New goal</button></div><div className="grid gap-4 md:grid-cols-2">{goals.map((g:Goal)=><div className="card p-5" key={g.id}><div className="flex justify-between"><div><b>{g.name}</b><small className="muted block">Target {g.targetDate}</small></div><div className="flex gap-2"><button onClick={()=>edit(g)} className="text-slate-500 hover:text-white"><Edit3 size={16}/></button><button onClick={()=>remove(g.id)} className="text-slate-500 hover:text-red-400"><Trash2 size={16}/></button></div></div><div className="mt-5 flex justify-between"><b>{money(g.currentAmount)}</b><span className="muted text-sm">of {money(g.targetAmount)}</span></div><div className="mt-3 h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-indigo-400" style={{width:`${Math.min(100,g.currentAmount/g.targetAmount*100)}%`}}/></div><div className="mt-2 text-right text-xs text-indigo-300">{Math.round(g.currentAmount/g.targetAmount*100)}% complete</div></div>)}</div></div>}
function Budgets({open}:any){const data=[["Food",8200,10000],["Shopping",5400,8000],["Transport",3200,6000],["Entertainment",2100,5000]];return <div className="space-y-7"><div className="flex justify-between"><div><div className="muted text-sm">Planning</div><h1 className="mt-1 text-3xl font-bold">Monthly budgets</h1></div><button onClick={open} className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-3 text-sm font-semibold"><Plus size={17}/> Create budget</button></div><div className="grid gap-4 md:grid-cols-2">{data.map(x=><div className="card p-5" key={x[0] as string}><div className="flex justify-between"><b>{x[0] as string}</b><span className="muted text-sm">{money(x[1] as number)} / {money(x[2] as number)}</span></div><div className="mt-5 h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-indigo-400" style={{width:`${Math.min(100,(x[1] as number)/(x[2] as number)*100)}%`}}/></div></div>)}</div></div>}
function Notifications({toast}:any){const [items,setItems]=useState(["RELIANCE moved +2.4%","Your food budget reached 82%","Investment successfully added"]);return <div className="space-y-7"><div className="flex justify-between"><h1 className="text-3xl font-bold">Notifications</h1><button onClick={()=>{setItems([]);toast("Notifications cleared")}} className="text-sm text-indigo-300">Clear all</button></div><div className="card">{items.length?items.map((x,i)=><div className="flex items-center gap-4 border-b border-white/5 p-5 last:border-0" key={i}><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-300"><Bell size={18}/></div><span className="flex-1">{x}<small className="muted block">Today</small></span><button onClick={()=>{setItems(a=>a.filter((_,j)=>j!==i));toast("Notification marked as read")}} className="text-xs text-slate-500 hover:text-white">Mark read</button></div>):<Empty title="All caught up" text="No unread notifications."/ >}</div></div>}
function SettingsPage({toast}:any){const [dark,setDark]=useState(true);return <div className="space-y-7"><h1 className="text-3xl font-bold">Settings</h1><div className="card divide-y divide-white/5"><div className="p-6"><b>Appearance</b><div className="mt-4 flex items-center justify-between rounded-2xl bg-white/[.025] p-4"><span><b className="text-sm">Dark mode</b><small className="muted block">Premium default theme</small></span><button onClick={()=>{setDark(!dark);toast(dark?"Light mode preference selected":"Dark mode preference selected")}} className={`h-7 w-12 rounded-full p-1 ${dark?"bg-indigo-500":"bg-slate-700"}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${dark?"translate-x-5":""}`}/></button></div></div><div className="p-6"><b>Account</b><p className="muted mt-2 text-sm">Tanay · tanay@finora.demo</p></div><div className="p-6"><b>Security</b><button onClick={()=>toast("Security check complete")} className="mt-4 block rounded-xl border border-white/10 px-4 py-3 text-sm hover:bg-white/5">Run security check</button></div></div></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="py-16 text-center col-span-full"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/5"><Star/></div><b className="mt-4 block">{title}</b><p className="muted mt-2 text-sm">{text}</p></div>}
function ModalShell({title,children,close}:any){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-5 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&close()}><motion.div initial={{y:15,scale:.98}} animate={{y:0,scale:1}} className="w-full max-w-md rounded-3xl border border-white/10 bg-[#111722] p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close}><X/></button></div>{children}</motion.div></motion.div>}
function InvestModal({s,close,buy}:any){const [amount,setAmount]=useState("10000");return <ModalShell title={`Invest in ${s.symbol}`} close={close}><div className="mt-5 rounded-xl bg-white/[.03] p-4"><span className="muted text-xs">Current price</span><b className="mt-1 block text-2xl">{money(s.currentPrice)}</b></div><label className="mt-5 block text-sm">Investment amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="1" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f17] p-3 outline-none"/></label><div className="muted mt-3 text-sm">Estimated shares: {((Number(amount)||0)/s.currentPrice).toFixed(4)}</div><button onClick={()=>buy(Number(amount))} className="mt-6 w-full rounded-xl bg-indigo-500 py-3 font-semibold">Confirm simulated investment</button><p className="muted mt-3 text-center text-xs">No real money is moved.</p></ModalShell>}
function TxModal({initial,close,save}:any){const [t,setT]=useState<any>(initial||{type:"EXPENSE",category:"Food",description:"",amount:0,date:today()});return <ModalShell title={initial?"Edit transaction":"Add transaction"} close={close}><div className="mt-5 space-y-4"><label className="block text-sm">Type<select value={t.type} onChange={e=>setT({...t,type:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f17] p-3"><option>EXPENSE</option><option>INCOME</option></select></label><Field label="Category" value={t.category} set={(v:string)=>setT({...t,category:v})} placeholder="Food"/><Field label="Description" value={t.description} set={(v:string)=>setT({...t,description:v})} placeholder="What was this for?"/><Field label="Amount" value={String(t.amount||"")} set={(v:string)=>setT({...t,amount:Number(v)})} placeholder="0"/><label className="block text-sm">Date<input type="date" value={t.date} onChange={e=>setT({...t,date:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f17] p-3"/></label><button onClick={()=>t.description&&t.amount>0&&save(t)} className="w-full rounded-xl bg-indigo-500 py-3 font-semibold">Save transaction</button></div></ModalShell>}
function IncomeModal({close,save}:any){const [amount,setAmount]=useState("75000");const [desc,setDesc]=useState("Monthly salary");return <ModalShell title="Add monthly income" close={close}><div className="mt-5 space-y-4"><Field label="Income source" value={desc} set={setDesc} placeholder="Salary"/><Field label="Monthly amount" value={amount} set={setAmount} placeholder="75000"/><label className="block text-sm">Date<input type="date" defaultValue={today()} id="incomeDate" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f17] p-3"/></label><button onClick={()=>save({type:"INCOME",category:"Salary",description:desc,amount:Number(amount),date:(document.getElementById("incomeDate") as HTMLInputElement)?.value||today()})} className="w-full rounded-xl bg-emerald-500 py-3 font-semibold">Add income</button></div></ModalShell>}
function GoalModal({initial,close,save}:any){const [g,setG]=useState<any>(initial||{name:"",targetAmount:100000,currentAmount:0,targetDate:today()});return <ModalShell title={initial?"Edit goal":"Create financial goal"} close={close}><div className="mt-5 space-y-4"><Field label="Goal name" value={g.name} set={(v:string)=>setG({...g,name:v})} placeholder="Emergency fund"/><Field label="Target amount" value={String(g.targetAmount)} set={(v:string)=>setG({...g,targetAmount:Number(v)})} placeholder="100000"/><Field label="Current saved" value={String(g.currentAmount)} set={(v:string)=>setG({...g,currentAmount:Number(v)})} placeholder="0"/><label className="block text-sm">Target date<input type="date" value={g.targetDate} onChange={e=>setG({...g,targetDate:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f17] p-3"/></label><button onClick={()=>g.name&&g.targetAmount>0&&save(g)} className="w-full rounded-xl bg-indigo-500 py-3 font-semibold">Save goal</button></div></ModalShell>}
function BudgetModal({close,toast}:any){const [name,setName]=useState("Travel");const [limit,setLimit]=useState("15000");return <ModalShell title="Create budget" close={close}><div className="mt-5 space-y-4"><Field label="Category" value={name} set={setName} placeholder="Travel"/><Field label="Monthly limit" value={limit} set={setLimit} placeholder="15000"/><button onClick={()=>{close();toast(`Budget created for ${name}`)}} className="w-full rounded-xl bg-indigo-500 py-3 font-semibold">Create budget</button></div></ModalShell>}

export default App;
